name: Test

on: [push, pull_request]

jobs:

  lint:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
        with:
          node-version-file: '.nvmrc'

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install NPM dependencies
        run: npm install

      - name: Start the Docker testing environment
        run: npm run wp-env start

      - name: Setup environment tools
        run: npm run setup:tools

      - name: Test
        run: npm test
